"""Census county list + collector coverage tracker.

Data lives under ``src/umbra/data/geo/`` (generated by
``scripts/generate_us_county_tracker.py``). Used to resolve
``Benton County, AR`` → FIPS / deep pack and to report L1/L2 rollup.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parents[3]
# Shipped with the package (not under gitignored /data/)
_PKG_GEO = Path(__file__).resolve().parent.parent / "data" / "geo"
_GEO_CANDIDATES = (
    _PKG_GEO,
    _REPO_ROOT / "data" / "geo",
)

_SUFFIX = re.compile(
    r"\s+(County|Parish|Borough|Census Area|Municipality|City and Borough|city)$",
    re.I,
)
_COUNTY_IN_BLOB = re.compile(
    r"\b([A-Za-z][A-Za-z.'\-]+(?:\s+[A-Za-z][A-Za-z.'\-]+){0,3})\s+"
    r"(County|Parish|Borough)\b",
    re.I,
)


def _geo_dir() -> Path:
    for d in _GEO_CANDIDATES:
        if (d / "us_counties_by_state.json").is_file():
            return d
    return _PKG_GEO


@lru_cache(maxsize=1)
def _compact() -> dict[str, list[dict[str, str]]]:
    path = _geo_dir() / "us_counties_by_state.json"
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


@lru_cache(maxsize=1)
def load_tracker() -> dict[str, Any]:
    path = _geo_dir() / "us_county_collector_tracker.json"
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def counties_for_state(abbr: str) -> list[dict[str, str]]:
    st = (abbr or "").strip().upper()
    return list(_compact().get(st) or [])


def coverage_rollup() -> dict[str, Any]:
    t = load_tracker()
    states = t.get("states") or {}
    total = sum(int(s.get("county_total") or 0) for s in states.values())
    deep = sum(int(s.get("county_deep") or 0) for s in states.values())
    l1 = sum(1 for s in states.values() if s.get("sos"))
    return {
        "states": len(states),
        "counties": total,
        "l1_state_packs": l1,
        "l2_county_deep": deep,
        "l2_open": max(0, total - deep),
    }


def _state_summary(block: dict[str, Any]) -> dict[str, Any]:
    return {
        "county_total": block.get("county_total"),
        "county_deep": block.get("county_deep"),
        "sos": bool(block.get("sos")),
        "courts": bool(block.get("courts")),
        "sor": bool(block.get("sor")),
    }


def _portal_health() -> dict[str, Any]:
    """Reachability of the portals behind the packs. Never raises."""
    try:
        from umbra.core.config import get_settings
        from umbra.people.portal_health import PortalHealth

        health = PortalHealth.from_settings(get_settings())
        try:
            return health.summary()
        finally:
            health.close()
    except Exception:  # noqa: BLE001 — coverage must render without the lake
        return {"checked": False, "fetchable": 0, "link_only": 0,
                "blocked_by_guard": 0, "broken": 0, "total": 0, "checked_at": None}


def coverage_payload(*, state: str | None = None, open_only: bool = False) -> dict[str, Any]:
    """Same rollup the CLI prints; used by `/people/coverage` and `/v1/people/coverage`."""
    roll = coverage_rollup()
    tracker = load_tracker()
    states = tracker.get("states") or {}
    summaries = {k: _state_summary(v) for k, v in states.items()}
    # "L2 deep 75" counts packs written. This counts portals a collector can
    # actually read, which is a smaller number and the one that predicts what an
    # investigation returns. Never checked is reported as never checked, not as
    # healthy.
    payload: dict[str, Any] = {
        "rollup": roll, "states": summaries, "portal_health": _portal_health(),
    }
    if not state:
        return payload
    st = state.strip().upper()
    block = states.get(st)
    if not block:
        payload["error"] = f"unknown state {st}"
        return payload
    counties = list(block.get("counties") or [])
    if open_only:
        counties = [c for c in counties if c.get("status") != "deep"]
    payload.update(
        {
            "state": st,
            "sos": bool(block.get("sos")),
            "courts": bool(block.get("courts")),
            "sor": bool(block.get("sor")),
            "county_total": block.get("county_total"),
            "county_deep": block.get("county_deep"),
            "counties": counties,
        }
    )
    return payload


def lookup_county(blob: str, state_abbr: str | None = None) -> dict[str, Any] | None:
    """Find a county from free text. Prefer explicit ``X County`` + state.

    Returns ``{name, fips, state, pack, status}`` or None.
    """
    text = (blob or "").strip()
    if len(text) < 3:
        return None
    st = (state_abbr or "").strip().upper() or None
    if not st:
        # trailing , ST
        m = re.search(r",\s*([A-Za-z]{2})\s*$", text)
        if m:
            st = m.group(1).upper()

    m = _COUNTY_IN_BLOB.search(text)
    want = None
    if m:
        want = m.group(1).strip()
    tracker = load_tracker()
    states = tracker.get("states") or {}

    def scan(abbr: str) -> dict[str, Any] | None:
        block = states.get(abbr) or {}
        for c in block.get("counties") or []:
            name = c.get("name") or ""
            bare = _SUFFIX.sub("", name).strip()
            if want:
                if want.lower() == bare.lower() or want.lower() in name.lower():
                    return {
                        "name": name,
                        "fips": c.get("fips"),
                        "state": abbr,
                        "pack": c.get("pack"),
                        "status": c.get("status") or "open",
                    }
            else:
                # city-style: "Bentonville" won't match; require County token
                continue
        return None

    if st and st in states:
        hit = scan(st)
        if hit:
            return hit
    if want:
        for abbr in sorted(states.keys()):
            hit = scan(abbr)
            if hit:
                return hit
    return None
